[package]
name = "iced_views"
version = "0.1.0"
edition = "2021"
description = "Stacked views logic for Iced application"
license-file = "LICENCE"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dev-dependencies]
iced = "0.8.0"
